### PR TITLE
fix: wrap titles and descriptions when needed

### LINKED ISSUE #519: Long descriptions hide the user's input
When an input description is too long (i.e. if it gets rendered on more than 2 lines) the user input gets lost.

```
package main

import (
	"github.com/charmbracelet/huh"
)

func main() {
	form := huh.NewForm(
		huh.NewGroup(
			huh.NewInput().
				Title("FieldName").
				Placeholder("Value").
				Description("This is a complicated field that requires a long winded description to fully grasp the intricacies of its ins and outs in each particular application. Ideally it should be possible to read the entirety of this description without the user's input disappearing."),
		),
	)

	form.Run()
}
```

Image
Image

(reproduced on `alacritty 0.15.0-dev` and `rxvt-unicode (urxvt) v9.30`)

### PR DESCRIPTION
**Pull request by caarlos0**
closes #519
closes #570

CleanShot 2025-03-12 at 16 44 15@2x

CleanShot 2025-03-12 at 17 03 22@2x

### CODE REVIEW

File: wrap.go [hunk 1]
```diff
@@ -0,0 +1,8 @@
+package huh
+
+import "github.com/charmbracelet/x/ansi"
+
+// TODO: replace with cellbuf.Wrap?
```
Comment (andreynering) [inline wrap.go:5]: `cellbuf.Wrap` is already released, so I think you can just use it.

File: examples/go.mod [hunk 2]
```diff
@@ -22,9 +22,11 @@ require (
 	github.com/aymanbagabas/go-osc52/v2 v2.0.1 // indirect
 	github.com/aymerick/douceur v0.2.0 // indirect
 	github.com/catppuccin/go v0.3.0 // indirect
+	github.com/charmbracelet/colorprofile v0.2.2 // indirect
 	github.com/charmbracelet/harmonica v0.2.0 // indirect
 	github.com/charmbracelet/keygen v0.5.1 // indirect
 	github.com/charmbracelet/x/ansi v0.8.0 // indirect
+	github.com/charmbracelet/x/cellbuf v0.0.12 // indirect
```
Comment (aymanbagabas) [inline examples/go.mod:29]: You wanna use the latest v0.0.13

**Review by aymanbagabas — APPROVED** [review]
Other than using cellbuf@v0.0.13, LGTM

**Comment by mrusme** [comment]
Tested with [this piece of code](https://github.com/mrusme/kopi/blob/5e00ff5aa8d4a52f78583aad921a5b3ac8c35dcb/cup/drink/cmd/tui.go#L65):

```sh
go get -u github.com/charmbracelet/huh@main && make
```

```go
		FormCup(
			cupDAO,
			&globCupEntity,
			"Drink Cup",
			"This wizard will guide through the steps to track a new cup"+
				" of coffee that was consumed.\nasdf asdf asdf sa fsad f sadfsad f asdf sad f sadfsad f asdfsdf sadfas f sa dfsadfsdf sa dfsadfas df sad fs df sdsd f ds fsd af asd f sd f sd f as f sda f sad f sda f sad f as df asdfasdf asd fas df s adfasdf sd f sad f sda f sd f sda fs asd fsafsdfsd f sdaf s daf sadfsadf sda f sadf sd af sadf sd f sd afsd f sad f sadfffffsdaffsadfsadf sdfsafsd f sdaf sadfasdfsdf sd f sdafsadfsdafs daf sadfsadf sadf asdfsdafs adf sd fsdafsadfsdafs adf sad f sdaffsdaf asdfsa dfsadfsadfsd fsdfsdfsadf sd fasdfsadfsd fsadfasdfsadf asdfasdf asdf sadfasdfasdfsadf sdafasdfsadfasdf sadf sda fasdfsadfsadfsdf asdf sadfsadfsadfsadf sdafsadfasdfsadfsad fsadfsadfsa dfasdfasdfsadfsdafsad fs dafasdfsadfsdafsdafsadfsdafsda fasdfsadfsadfsdafs dafasdfsdafsdafsdfsd f sdafsdafsadfsadfsadfsadfsadfsadf sdafsadfsdafsadfsdaf safd fasdfsdfasdfsadfsad fsadfsadfsadfsadfsdf sdf sadfad",
			accessible,
		)

....

		form := huh.NewForm(
			huh.NewGroup(
				huh.NewNote().
					Title(title).
					Description(description).
					Next(true).
					NextLabel("Let's go!"),
			),
...
```

screenshot_2025-03-14-140154

Did I miss anything?

**Comment by caarlos0** [comment]
I cannot reproduce this.

Can you create a minimal reproducible for it? Something like [this](https://github.com/charmbracelet/huh/blob/main/examples/issue-519/main.go).

Also, can you try it on https://github.com/charmbracelet/huh/pull/573 ?

```sh
go get github.com/charmbracelet/huh@height
```

**Comment by mrusme** [comment]
Thank you for your suggestion.

> Also, can you try it on https://github.com/charmbracelet/huh/pull/573 ?

I used the `height` branch with the previously described code and I can confirm that the button shows now. This means that the branch you linked is also necessary for https://github.com/charmbracelet/huh/issues/538 to work.
